### ISSUE TITLE
Couldn't find preset "env"

### ISSUE THREAD

**Issue by remicastaing** [goldwasserexchange/serverless-plugin-webpack#18]
I ran `sls package`and got following error:
```
ERROR in ./things/handler.js
    Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/remi/Workspaces/angular-serverless/back/things"
        at /Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (native)
        at OptionManager.resolvePresets (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-loader/lib/index.js:48:20)
        at Object.module.exports (/Users/remi/Workspaces/angular-serverless/back/node_modules/babel-loader/lib/index.js:163:20)
```

**Comment by remicastaing** [comment]
Ok, I found it: I had to add `babel-preset-env`and `babel-preset`stage0`.
