### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by nachbarshund** [goldwasserexchange/serverless-plugin-webpack#39]
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at R.map.R.over.artifact (/Users/christopher/myproject/node_modules/serverless-plugin-webpack/src/lib/service.js:30:48)
```

### Environment

```
Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.2
     Serverless Version:     1.15.3
```

Any solution for this problem?

**Comment by jogold** [comment]
Hi @nachbarshund,

The latest version of the plugin requires serverless v1.18.0 or higher.
